import type { Metadata } from "next";
import { Barlow, REM } from "next/font/google";
import "./globals.css";

// Charger Barlow pour le body (plusieurs poids)
const barlow = Barlow({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-heading", // => crée une classe qui définit la var CSS
  display: "swap",
});

// Charger REM pour les titres / branding
const rem = REM({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "FinCollect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${rem.variable}`}>{children}</body>
    </html>
  );
}
